### ISSUE TITLE
slides: feedback

### ISSUE THREAD

**Issue by michaelsevilla** [michaelsevilla/noitatressid#32]

**Comment by tidalscale-nassi** [comment]
1. Hierarchical file systems were introduced many years prior to 1985.
1. "millions of filesystems" -- overstated, surely.
1. "he"? should say "he or she"
1.  good point about the "nightmare" of selecting new file systems based on data reuse
1.  I like the idea of the filesystem "rearranging" its metadata and its management
1.  Probably should distinguish between two things: physical namespace structure, and what the user thinks of as the namespace structure.  They do not need to be the same thing.  [think chroot which treats it virtually]
1. I suggest you motivate the distribution of metadata a bit more.  Why distribute metadata at all?  why not centralize it?  Or replicate it?
1. What is the universal metric?  I suggest it's really application elapsed time rather than measuring load on a metadata server.
1.  What you're doing in some of this could be called "machine learning".  Why not say these words?
1. You're making it seem like there is a choice (e.g. strong, weak, invisible).  But is this really a choice?  Isn't it a requirement of the application using this stuff?  From the application POV it's not a choice at all!
1. Thin provisioned namespaces akin to thin provisioned storage
1. Also funded by SAP
1. There is no real discussion I saw about the complexity of the API's or how to manage high complexity.  For example, if you are in a short-circuited strategy determination, you may be able to reduce the overhead so that you only determine state if you're in a nested "if" control structure.

**Comment by jlefevre** [comment]
Slide 12, Solution 1, 2,3 might want to specify these are "existing/current" solutions or approaches.  Similarly on slide 13 as title changes from (existing solution) Ceph's subtree.. to (our solution) Mantle ... 
In general make sure to clarify which are your contributions/solutions vs. what exists now.

Slide 15, same thing.  Maybe add subtitle of "Implementation of 3 MDS load balancing policies with Mantle." or something to that effect.  This also highlights the fact that Mantle is flexible enough to enable many policies within a single system, which addresses the problem that you started out with: showing so many specialized systems developed with different but fixed policies.

Slide 19:  "Clients can:"  again I think (?) this refers to "with Cudele, clients can":...
Slide 20:  "mapping decoupled namespaces to Ceph with Cudele". ?
Slide 21:  "building consistency guarantees with Cudle by ...."
Slide 30:  conclusion slide. You should point out that you built a system(s) for each of these (1) (2) that has the ability to tune for different policies and you evaluated them within the same (single) system, and maybe show the original timeline graph again (small pic) with all the specialized systems, the design points for several of which you show can be flexibly incorporated within a single system via your work.

**Comment by reza-nasirigerdeh** [comment]
General:

1. In the outline box (the right-hand box of all slides), the sections presented were struck through. I think It is a good idea to keep them unchanged and only highlight the section you are presenting.
2. Phrases such as Metadata Server are used frequently  with a big font and made little space available for the figures in the slides. I think you should you abbreviations (e.g. MDS for metadata server) instead of the phrases themselves.

Slide 4:
client and metadata server has similar symbols (green square). You should use different symbols for them.

Slide (Related Work)
To my knowledge, one of the recent works on the metadata management of distributed file systems has been done at CMU (Fast Storage for File System Metadata, PhD thesis of Kai Ren advised by Garth Gibson). I think it is  good idea to mention it in your related work.

Slide 12:
X and Y lables of the two top figures (Metadata req/s and Time ) are far from the figures.

Slide 15:
I think you should make it much more clear that your point is to show how we can easily implement different policies using mantle not the performance of the different policies.
